language: python

python:
  - "2.7"
  - "3.4"
  
#virtualenv:
#  system_site_packages: true

matrix:
  allow_failures:
    # unfortunately couldn't find a reliable way to test pyqt5 on travis yet
    - env: PYTEST_VERSION=2.7.0 PYTEST_QT_API=pyqt5

env:
 #- PYTEST_VERSION=2.6.4 PYTEST_QT_API=pyqt4
 #- PYTEST_VERSION=2.6.4 PYTEST_QT_API=pyside
 #- PYTEST_VERSION=2.7.0 PYTEST_QT_API=pyqt4
 #- PYTEST_VERSION=2.7.0 PYTEST_QT_API=pyside
 - PYTEST_VERSION=2.7.0 PYTEST_QT_API=pyqt5

install:
 - sudo apt-get update

 - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
     wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
   else
     wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
   fi

 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda config --add channels jdreaver
 # Useful for debugging any issues with conda
 - conda info -a

 - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pyqt5
 - source activate test-environment
 - python setup.py develop

 # PyTest
 - pip uninstall -y pytest
 - pip install pytest==$PYTEST_VERSION

 # others
 - pip install coveralls --use-wheel

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

script:
 - coverage run --source=pytestqt setup.py test

after_success:
 - coveralls
